In [ ]:
import pandas as pd
import pyarrow.parquet as pq
from pathlib import Path

# Ruta de tu dataset final reducido
DATASET_PATH = Path(r"D:\GB TI\Master\Visu_DATOS\Proyecto\project_hpc_visdatos\VisDatos_HPC\data\raw\datacenter_enriched_core_single.parquet")

# Leer metadata sin cargar todo el dataset
pf = pq.ParquetFile(DATASET_PATH)

print("Archivo:")
print(DATASET_PATH)

print("\nNúmero de filas:")
print(pf.metadata.num_rows)

print("\nNúmero de columnas:")
print(len(pf.schema.names))

print("\nColumnas del dataset:")
for i, col in enumerate(pf.schema.names, start=1):
    print(f"{i}. {col}")

Archivo:
D:\GB TI\Master\Visu_DATOS\Proyecto\data\datacenter_enriched_core_single.parquet

Número de filas:
11930727

Número de columnas:
53

Columnas del dataset:
1. prom_id
2. timestamp
3. timestamp_seconds
4. timestamp_seconds_delta
5. node
6. rack_inferred
7. node_position_inferred
8. gpu_node
9. gpu_model
10. gpu_count
11. cpu_tdp_total
12. gpu_tdp_total
13. node_load1
14. node_load5
15. node_load15
16. node_load1_per_core
17. node_power_usage
18. node_rapl_package_power_sum
19. node_rapl_package_joules_total_sum_delta
20. cpu_package_energy_kwh
21. node_memory_Active_bytes
22. node_memory_MemFree_bytes
23. ram_active_gb
24. ram_free_gb
25. node_hwmon_temp_celsius_mean
26. node_hwmon_temp_celsius_max
27. node_thermal_zone_temp_mean
28. node_thermal_zone_temp_max
29. nvidia_gpu_memory_used_bytes_sum
30. gpu_memory_used_gb
31. nvidia_gpu_temperature_celsius_mean
32. nvidia_gpu_temperature_celsius_max
33. nvidia_gpu_power_usage_milliwatts_mean
34. gpu_power_watts_mean
35. gpu_power_watts_max
36. nvidia_gpu_duty_cycle_mean
37. nvidia_gpu_duty_cycle_max
38. node_disk_read_bytes_total_sum_delta
39. node_disk_written_bytes_total_sum_delta
40. node_network_receive_bytes_total_sum_delta
41. node_network_transmit_bytes_total_sum_delta
42. node_energy_kwh_est
43. gpu_energy_kwh_est
44. co2_kg_est
45. slurm_id
46. start_date
47. end_date
48. job_duration_hours
49. state
50. nodetypes
51. numnodes
52. numcores
53. slurm_nodes

In [2]:
# Cargar dataset
df_core = pd.read_parquet(DATASET_PATH)

print("Dimensiones del dataset:")
print(df_core.shape)

print("\nPrimeras filas:")
display(df_core.head())

print("\nÚltimas filas:")
display(df_core.tail())

Dimensiones del dataset:
(11930727, 53)

Primeras filas:

,prom_id,timestamp,timestamp_seconds,timestamp_seconds_delta,node,rack_inferred,node_position_inferred,gpu_node,gpu_model,gpu_count,...,co2_kg_est,slurm_id,start_date,end_date,job_duration_hours,state,nodetypes,numnodes,numcores,slurm_nodes
0,21988367,2022-07-28 22:58:30,1659049110,30.0,r26n7,r26,n7,0,n/a,0,...,0.000387,1740264,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056,COMPLETED,normal(1),1,16,['r26n7']
1,21988368,2022-07-28 22:59:00,1659049140,30.0,r26n7,r26,n7,0,n/a,0,...,0.000387,1740264,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056,COMPLETED,normal(1),1,16,['r26n7']
2,21988369,2022-07-28 22:59:30,1659049170,30.0,r26n7,r26,n7,0,n/a,0,...,0.000387,1740264,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056,COMPLETED,normal(1),1,16,['r26n7']
3,21988370,2022-07-28 23:00:00,1659049200,30.0,r26n7,r26,n7,0,n/a,0,...,0.000387,1740264,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056,COMPLETED,normal(1),1,16,['r26n7']
4,21988371,2022-07-28 23:00:30,1659049230,30.0,r26n7,r26,n7,0,n/a,0,...,0.000387,1740264,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056,COMPLETED,normal(1),1,16,['r26n7']

Últimas filas:

,prom_id,timestamp,timestamp_seconds,timestamp_seconds_delta,node,rack_inferred,node_position_inferred,gpu_node,gpu_model,gpu_count,...,co2_kg_est,slurm_id,start_date,end_date,job_duration_hours,state,nodetypes,numnodes,numcores,slurm_nodes
11930722,73726913,2022-09-07 12:29:30,1662553770,30.0,r26n9,r26,n9,0,n/a,0,...,0.000347,1969590,2022-09-05 08:01:14,2022-09-09 12:21:18,100.334444,TIMEOUT,normal(1),1,16,['r26n9']
11930723,73726914,2022-09-07 12:30:00,1662553800,30.0,r26n9,r26,n9,0,n/a,0,...,0.000347,1969590,2022-09-05 08:01:14,2022-09-09 12:21:18,100.334444,TIMEOUT,normal(1),1,16,['r26n9']
11930724,73726915,2022-09-07 12:30:30,1662553830,30.0,r26n9,r26,n9,0,n/a,0,...,0.000347,1969590,2022-09-05 08:01:14,2022-09-09 12:21:18,100.334444,TIMEOUT,normal(1),1,16,['r26n9']
11930725,73726916,2022-09-07 12:31:00,1662553860,30.0,r26n9,r26,n9,0,n/a,0,...,0.000347,1969590,2022-09-05 08:01:14,2022-09-09 12:21:18,100.334444,TIMEOUT,normal(1),1,16,['r26n9']
11930726,73726917,2022-09-07 12:31:30,1662553890,30.0,r26n9,r26,n9,0,n/a,0,...,0.000347,1969590,2022-09-05 08:01:14,2022-09-09 12:21:18,100.334444,TIMEOUT,normal(1),1,16,['r26n9']

In [ ]:
# Revisa tipos de datos
print("Tipos de datos por columna:")
display(df_core.dtypes.reset_index().rename(columns={"index": "columna", 0: "tipo_dato"}))

Tipos de datos por columna:

                                        columna       tipo_dato
0                                       prom_id  string[python]
1                                     timestamp  datetime64[ns]
2                             timestamp_seconds           int64
3                       timestamp_seconds_delta         float32
4                                          node  string[python]
5                                 rack_inferred  string[python]
6                        node_position_inferred  string[python]
7                                      gpu_node           int32
8                                     gpu_model  string[python]
9                                     gpu_count           int32
10                                cpu_tdp_total         float64
11                                gpu_tdp_total         float64
12                                   node_load1         float64
13                                   node_load5         float64
14                                  node_load15         float64
15                          node_load1_per_core         float64
16                             node_power_usage         float64
17                  node_rapl_package_power_sum         float64
18     node_rapl_package_joules_total_sum_delta         float64
19                       cpu_package_energy_kwh         float64
20                     node_memory_Active_bytes         float64
21                    node_memory_MemFree_bytes         float64
22                                ram_active_gb         float64
23                                  ram_free_gb         float64
24                 node_hwmon_temp_celsius_mean         float64
25                  node_hwmon_temp_celsius_max         float64
26                  node_thermal_zone_temp_mean         float64
27                   node_thermal_zone_temp_max         float64
28             nvidia_gpu_memory_used_bytes_sum         float64
29                           gpu_memory_used_gb         float64
30          nvidia_gpu_temperature_celsius_mean         float64
31           nvidia_gpu_temperature_celsius_max         float64
32       nvidia_gpu_power_usage_milliwatts_mean         float64
33                         gpu_power_watts_mean         float64
34                          gpu_power_watts_max         float64
35                   nvidia_gpu_duty_cycle_mean         float64
36                    nvidia_gpu_duty_cycle_max         float64
37         node_disk_read_bytes_total_sum_delta         float64
38      node_disk_written_bytes_total_sum_delta         float64
39   node_network_receive_bytes_total_sum_delta         float64
40  node_network_transmit_bytes_total_sum_delta         float64
41                          node_energy_kwh_est         float64
42                           gpu_energy_kwh_est         float64
43                                   co2_kg_est         float64
44                                     slurm_id  string[python]
45                                   start_date  datetime64[ns]
46                                     end_date  datetime64[ns]
47                           job_duration_hours         float64
48                                        state  string[python]
49                                    nodetypes  string[python]
50                                     numnodes           int64
51                                     numcores           int64
52                                  slurm_nodes  string[python]

In [ ]:
# Revisa valores nulos
null_summary = pd.DataFrame({
    "columna": df_core.columns,
    "nulos": df_core.isna().sum().values,
    "porcentaje_nulos": (df_core.isna().mean().values * 100).round(2)
})

null_summary = null_summary.sort_values("porcentaje_nulos", ascending=False)

print("Resumen de valores nulos:")
display(null_summary)

Resumen de valores nulos:

                                        columna  nulos  porcentaje_nulos
0                                       prom_id      0               0.0
27                   node_thermal_zone_temp_max      0               0.0
29                           gpu_memory_used_gb      0               0.0
30          nvidia_gpu_temperature_celsius_mean      0               0.0
31           nvidia_gpu_temperature_celsius_max      0               0.0
32       nvidia_gpu_power_usage_milliwatts_mean      0               0.0
33                         gpu_power_watts_mean      0               0.0
34                          gpu_power_watts_max      0               0.0
35                   nvidia_gpu_duty_cycle_mean      0               0.0
36                    nvidia_gpu_duty_cycle_max      0               0.0
37         node_disk_read_bytes_total_sum_delta      0               0.0
38      node_disk_written_bytes_total_sum_delta      0               0.0
39   node_network_receive_bytes_total_sum_delta      0               0.0
40  node_network_transmit_bytes_total_sum_delta      0               0.0
41                          node_energy_kwh_est      0               0.0
42                           gpu_energy_kwh_est      0               0.0
43                                   co2_kg_est      0               0.0
44                                     slurm_id      0               0.0
45                                   start_date      0               0.0
46                                     end_date      0               0.0
47                           job_duration_hours      0               0.0
48                                        state      0               0.0
49                                    nodetypes      0               0.0
50                                     numnodes      0               0.0
51                                     numcores      0               0.0
28             nvidia_gpu_memory_used_bytes_sum      0               0.0
26                  node_thermal_zone_temp_mean      0               0.0
1                                     timestamp      0               0.0
25                  node_hwmon_temp_celsius_max      0               0.0
2                             timestamp_seconds      0               0.0
3                       timestamp_seconds_delta      0               0.0
4                                          node      0               0.0
5                                 rack_inferred      0               0.0
6                        node_position_inferred      0               0.0
7                                      gpu_node      0               0.0
8                                     gpu_model      0               0.0
9                                     gpu_count      0               0.0
10                                cpu_tdp_total      0               0.0
11                                gpu_tdp_total      0               0.0
12                                   node_load1      0               0.0
13                                   node_load5      0               0.0
14                                  node_load15      0               0.0
15                          node_load1_per_core      0               0.0
16                             node_power_usage      0               0.0
17                  node_rapl_package_power_sum      0               0.0
18     node_rapl_package_joules_total_sum_delta      0               0.0
19                       cpu_package_energy_kwh      0               0.0
20                     node_memory_Active_bytes      0               0.0
21                    node_memory_MemFree_bytes      0               0.0
22                                ram_active_gb      0               0.0
23                                  ram_free_gb      0               0.0
24                 node_hwmon_temp_celsius_mean      0               0.0
52                                  slurm_nodes      0               0.0

In [ ]:
# Revisa columnas numéricas principales
numeric_cols = df_core.select_dtypes(include=["number"]).columns

print("Columnas numéricas:")
print(list(numeric_cols))

print("\nEstadísticas descriptivas:")
display(df_core[numeric_cols].describe().T)

Columnas numéricas:
['timestamp_seconds', 'timestamp_seconds_delta', 'gpu_node', 'gpu_count', 'cpu_tdp_total', 'gpu_tdp_total', 'node_load1', 'node_load5', 'node_load15', 'node_load1_per_core', 'node_power_usage', 'node_rapl_package_power_sum', 'node_rapl_package_joules_total_sum_delta', 'cpu_package_energy_kwh', 'node_memory_Active_bytes', 'node_memory_MemFree_bytes', 'ram_active_gb', 'ram_free_gb', 'node_hwmon_temp_celsius_mean', 'node_hwmon_temp_celsius_max', 'node_thermal_zone_temp_mean', 'node_thermal_zone_temp_max', 'nvidia_gpu_memory_used_bytes_sum', 'gpu_memory_used_gb', 'nvidia_gpu_temperature_celsius_mean', 'nvidia_gpu_temperature_celsius_max', 'nvidia_gpu_power_usage_milliwatts_mean', 'gpu_power_watts_mean', 'gpu_power_watts_max', 'nvidia_gpu_duty_cycle_mean', 'nvidia_gpu_duty_cycle_max', 'node_disk_read_bytes_total_sum_delta', 'node_disk_written_bytes_total_sum_delta', 'node_network_receive_bytes_total_sum_delta', 'node_network_transmit_bytes_total_sum_delta', 'node_energy_kwh_est', 'gpu_energy_kwh_est', 'co2_kg_est', 'job_duration_hours', 'numnodes', 'numcores']

Estadísticas descriptivas:

,count,mean,std,min,25%,50%,75%,max
timestamp_seconds,11930727.0,1.662465e+09,2.716637e+06,1.656608e+09,1.660524e+09,1.662615e+09,1.664802e+09,1.667307e+09
timestamp_seconds_delta,11930727.0,3.066801e+01,7.023035e+01,3.000000e+01,3.000000e+01,3.000000e+01,3.000000e+01,1.521000e+04
gpu_node,11930727.0,2.331844e-01,4.228586e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
gpu_count,11930727.0,9.327375e-01,1.691435e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
cpu_tdp_total,11930727.0,1.549393e+02,3.174128e+01,1.250000e+02,1.250000e+02,1.700000e+02,1.700000e+02,2.100000e+02
gpu_tdp_total,11930727.0,2.528291e+02,4.592480e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.120000e+03
node_load1,11930727.0,1.175441e+01,2.654258e+01,0.000000e+00,2.480000e+00,1.100000e+01,1.560000e+01,2.446860e+03
node_load5,11930727.0,1.173119e+01,2.633747e+01,0.000000e+00,2.700000e+00,1.092000e+01,1.539000e+01,2.438310e+03
node_load15,11930727.0,1.167549e+01,2.600178e+01,0.000000e+00,3.000000e+00,1.079000e+01,1.522000e+01,2.421850e+03
node_load1_per_core,11930727.0,1.654823e+00,3.320564e+00,0.000000e+00,1.008125e-01,7.300000e-01,2.002500e+00,1.809300e+02
node_power_usage,11930727.0,3.250437e+02,3.914337e+02,3.200000e+01,1.160000e+02,1.520000e+02,1.920000e+02,1.680000e+03
node_rapl_package_power_sum,11930727.0,7.765278e+01,3.146588e+01,0.000000e+00,5.769867e+01,8.187033e+01,1.008263e+02,1.369723e+04
node_rapl_package_joules_total_sum_delta,11930727.0,2.329792e+03,9.437392e+02,0.000000e+00,1.731150e+03,2.456160e+03,3.024850e+03,4.109168e+05
cpu_package_energy_kwh,11930727.0,6.471645e-04,2.621498e-04,0.000000e+00,4.808750e-04,6.822667e-04,8.402361e-04,1.141435e-01
node_memory_Active_bytes,11930727.0,1.949541e+10,1.918748e+10,8.248520e+07,4.021090e+09,1.438400e+10,3.185090e+10,2.098550e+11
node_memory_MemFree_bytes,11930727.0,9.874020e+10,5.009026e+10,2.944940e+08,6.642490e+10,9.153120e+10,9.705910e+10,2.679670e+11
ram_active_gb,11930727.0,1.815652e+01,1.786973e+01,7.682033e-02,3.744932e+00,1.339614e+01,2.966346e+01,1.954427e+02
ram_free_gb,11930727.0,9.195898e+01,4.665019e+01,2.742689e-01,6.186301e+01,8.524507e+01,9.039333e+01,2.495637e+02
node_hwmon_temp_celsius_mean,11930727.0,3.969175e+01,1.011208e+01,2.139000e+01,3.031000e+01,4.011000e+01,4.759000e+01,7.141000e+01
node_hwmon_temp_celsius_max,11930727.0,4.306388e+01,9.946693e+00,2.400000e+01,3.500000e+01,4.400000e+01,5.000000e+01,7.300000e+01
node_thermal_zone_temp_mean,11930727.0,4.229307e+01,9.859229e+00,2.250000e+01,3.450000e+01,4.400000e+01,4.950000e+01,7.600000e+01
node_thermal_zone_temp_max,11930727.0,4.324970e+01,9.940631e+00,2.300000e+01,3.600000e+01,4.400000e+01,5.000000e+01,7.600000e+01
nvidia_gpu_memory_used_bytes_sum,11930727.0,7.584916e+09,1.828216e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.008180e+11
gpu_memory_used_gb,11930727.0,7.064003e+00,1.702659e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.389404e+01
nvidia_gpu_temperature_celsius_mean,11930727.0,1.272683e+01,2.442651e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.675000e+01
nvidia_gpu_temperature_celsius_max,11930727.0,1.592212e+01,3.017177e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.300000e+01
nvidia_gpu_power_usage_milliwatts_mean,11930727.0,2.963808e+04,6.514519e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.136902e+05
gpu_power_watts_mean,11930727.0,2.963808e+01,6.514519e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.136902e+02
gpu_power_watts_max,11930727.0,4.668497e+01,9.563651e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.139220e+02
nvidia_gpu_duty_cycle_mean,11930727.0,1.029763e+01,2.431030e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+02
nvidia_gpu_duty_cycle_max,11930727.0,1.674188e+01,3.511348e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+02
node_disk_read_bytes_total_sum_delta,11930727.0,1.886899e+07,4.363660e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.462741e+10
node_disk_written_bytes_total_sum_delta,11930727.0,4.994326e+07,6.547269e+08,0.000000e+00,2.611200e+04,4.454400e+04,1.059840e+05,5.630090e+10
node_network_receive_bytes_total_sum_delta,11930727.0,2.712689e+08,1.285756e+09,0.000000e+00,5.022000e+03,1.303800e+04,5.652905e+05,2.323736e+11
node_network_transmit_bytes_total_sum_delta,11930727.0,2.620388e+08,1.188439e+09,0.000000e+00,3.464800e+04,5.489800e+04,1.207842e+06,2.324729e+11
node_energy_kwh_est,11930727.0,2.708849e-03,3.262623e-03,2.666667e-04,9.666667e-04,1.266667e-03,1.600000e-03,8.600000e-02
gpu_energy_kwh_est,11930727.0,2.469920e-04,5.429612e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.557112e-02
co2_kg_est,11930727.0,1.083539e-03,1.305049e-03,1.066667e-04,3.866667e-04,5.066667e-04,6.400000e-04,3.440000e-02
job_duration_hours,11930727.0,5.315612e+01,4.250765e+01,0.000000e+00,1.200333e+01,4.404472e+01,9.511167e+01,1.210078e+02
numnodes,11930727.0,2.358040e+00,3.745616e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,3.200000e+01
numcores,11930727.0,3.291527e+01,6.193572e+01,1.000000e+00,4.000000e+00,1.600000e+01,1.600000e+01,5.120000e+02

In [ ]:
# Revisa columnas categóricas 
categorical_cols = df_core.select_dtypes(include=["object", "string", "category"]).columns

print("Columnas categóricas:")
print(list(categorical_cols))

for col in categorical_cols:
    print(f"\nColumna: {col}")
    print(df_core[col].value_counts(dropna=False).head(20))

Columnas categóricas:
['prom_id', 'node', 'rack_inferred', 'node_position_inferred', 'gpu_model', 'slurm_id', 'state', 'nodetypes', 'slurm_nodes']

Columna: prom_id
prom_id
75435331    32
76423022    32
83096009    32
83096010    32
76423013    32
76423014    32
76423015    32
76423016    32
76423017    32
76423018    32
76423019    32
76423020    32
76423021    32
76423023    32
83096007    32
76423024    32
76423025    32
76423026    32
76423027    32
76423028    32
Name: count, dtype: Int64

Columna: node
node
r28n1     416973
r11n27    398672
r12n22    385011
r12n15    321633
r34n1     319698
r15n17    317827
r10n31    302379
r12n1     289905
r11n26    283501
r13n29    280515
r29n3     280190
r15n30    276409
r27n16    275927
r10n17    272985
r25n13    272334
r26n14    271606
r10n8     271042
r26n23    268243
r36n2     266002
r11n11    255583
Name: count, dtype: Int64

Columna: rack_inferred
rack_inferred
r26    1998069
r11    1598012
r10    1452933
r12    1234615
r15     987961
r25     904390
r34     538299
r27     517086
r36     475866
r29     469521
r32     469336
r13     455602
r28     416973
r33     412064
Name: count, dtype: Int64

Columna: node_position_inferred
node_position_inferred
n3     1479546
n1     1026576
n17     784032
n30     663276
n2      613385
n29     534678
n9      522151
n8      520915
n31     517375
n14     453243
n22     437629
n16     428706
n4      426143
n13     402271
n27     398672
n15     375334
n18     367002
n7      316145
n26     283501
n28     271559
Name: count, dtype: Int64

Columna: gpu_model
gpu_model
n/a                           9148668
NVIDIA_TITAN_RTX              1953136
NVIDIA_GeForce_GTX_1080_Ti     828923
Name: count, dtype: Int64

Columna: slurm_id
slurm_id
1599303    33212
1823129    32751
1587179    31732
2318840    28562
1606864    23449
1924356    22868
1620081    22240
2142515    22148
1682713    19242
1600477    18354
2083938    18088
1876667    17232
1696919    16608
1729008    16556
1988614    14428
2140225    14401
2186455    14401
2140229    14401
2140227    14401
2140104    14401
Name: count, dtype: Int64

Columna: state
state
COMPLETED        6296756
TIMEOUT          3641367
CANCELLED        1132963
FAILED            544125
NODE_FAIL         232440
OUT_OF_MEMORY      83076
Name: count, dtype: Int64

Columna: nodetypes
nodetypes
normal(1)                        4615186
shared(1)                        2536406
gpu_titanrtx_shared(1)           1799090
gpu_shared(1)                     733688
normal(10)                        507046
normal(16)                        482272
normal(3)                         413384
gpu_titanrtx(1)                   142287
normal(4)                         110565
normal(2)                         103142
normal(12)                         97512
normal(8)                          85811
gpu(1)                             80929
normal(5)                          65272
normal(20)                         45460
shared(5)                          21951
shared_jupyter(1)                  20267
shared(2)                          16563
gpu_titanrtx_shared_course(1)      11672
gpu_shared_course(1)                9532
Name: count, dtype: Int64

Columna: slurm_nodes
slurm_nodes
['r28n1']     416973
['r12n22']    346174
['r34n1']     319662
['r11n27']    301231
['r15n17']    293812
['r29n3']     280153
['r12n15']    276915
['r36n2']     266001
['r10n31']    261658
['r13n29']    261261
['r12n1']     252628
['r10n17']    240561
['r32n4']     236379
['r33n3']     230434
['r11n26']    224168
['r15n30']    222273
['r25n13']    220211
['r11n28']    218646
['r34n2']     218601
['r10n8']     216915
Name: count, dtype: Int64

In [ ]:
# Revisa el rango temporal
df_core["timestamp"] = pd.to_datetime(df_core["timestamp"], errors="coerce")
df_core["start_date"] = pd.to_datetime(df_core["start_date"], errors="coerce")
df_core["end_date"] = pd.to_datetime(df_core["end_date"], errors="coerce")

print("Rango temporal de mediciones:")
print(df_core["timestamp"].min(), "→", df_core["timestamp"].max())

print("\nRango de inicio de jobs:")
print(df_core["start_date"].min(), "→", df_core["start_date"].max())

print("\nRango de fin de jobs:")

print(df_core["end_date"].min(), "→", df_core["end_date"].max())

Rango temporal de mediciones:
2022-06-30 16:55:30 → 2022-11-01 12:46:30

Rango de inicio de jobs:
2022-06-30 16:55:10 → 2022-11-01 11:31:07

Rango de fin de jobs:
2022-06-30 16:59:18 → 2022-11-01 12:46:31

In [ ]:
# Validación de timestamp dentro del job
df_core["timestamp_dentro_del_job"] = (
    (df_core["timestamp"] >= df_core["start_date"]) &
    (df_core["timestamp"] <= df_core["end_date"])
)

print("Validación timestamp dentro del job:")
print(df_core["timestamp_dentro_del_job"].value_counts(dropna=False))

Validación timestamp dentro del job:
timestamp_dentro_del_job
True    11930727
Name: count, dtype: int64

In [9]:
print("Cantidad de nodos únicos:")
print(df_core["node"].nunique())

print("\nPrimeros nodos:")
print(df_core["node"].drop_duplicates().head(30).to_list())

print("\nRacks inferidos:")
print(df_core["rack_inferred"].value_counts(dropna=False).head(20))

print("\nDistribución CPU/GPU:")
print(df_core["gpu_node"].value_counts(dropna=False))

print("\nModelos GPU:")
print(df_core["gpu_model"].value_counts(dropna=False).head(20))

print("\nCantidad de GPU por nodo:")
print(df_core["gpu_count"].value_counts(dropna=False))

Cantidad de nodos únicos:
62

Primeros nodos:
['r26n7', 'r26n8', 'r26n9', 'r11n10', 'r11n11', 'r11n12', 'r15n3', 'r15n30', 'r15n31', 'r11n9', 'r12n1', 'r11n27', 'r11n28', 'r10n17', 'r10n18', 'r13n28', 'r13n29', 'r13n3', 'r27n9', 'r28n1', 'r26n3', 'r26n30', 'r26n31', 'r12n21', 'r12n22', 'r10n30', 'r10n31', 'r10n32', 'r29n3', 'r29n4']

Racks inferidos:
rack_inferred
r26    1998069
r11    1598012
r10    1452933
r12    1234615
r15     987961
r25     904390
r34     538299
r27     517086
r36     475866
r29     469521
r32     469336
r13     455602
r28     416973
r33     412064
Name: count, dtype: Int64

Distribución CPU/GPU:
gpu_node
0    9148668
1    2782059
Name: count, dtype: int64

Modelos GPU:
gpu_model
n/a                           9148668
NVIDIA_TITAN_RTX              1953136
NVIDIA_GeForce_GTX_1080_Ti     828923
Name: count, dtype: Int64

Cantidad de GPU por nodo:
gpu_count
0    9148668
4    2782059
Name: count, dtype: int64

In [ ]:

print("Cantidad de jobs SLURM únicos:")
print(df_core["slurm_id"].nunique())

print("\nEstados de jobs:")
print(df_core["state"].value_counts(dropna=False))

print("\nTipos de nodo usados en jobs:")
print(df_core["nodetypes"].value_counts(dropna=False).head(20))

print("\nNúmero de nodos por job:")
display(df_core["numnodes"].describe())

print("\nNúmero de cores por job:")
display(df_core["numcores"].describe())

print("\nDuración de jobs en horas:")
display(df_core["job_duration_hours"].describe())

Cantidad de jobs SLURM únicos:
31442

Estados de jobs:
state
COMPLETED        6296756
TIMEOUT          3641367
CANCELLED        1132963
FAILED            544125
NODE_FAIL         232440
OUT_OF_MEMORY      83076
Name: count, dtype: Int64

Tipos de nodo usados en jobs:
nodetypes
normal(1)                        4615186
shared(1)                        2536406
gpu_titanrtx_shared(1)           1799090
gpu_shared(1)                     733688
normal(10)                        507046
normal(16)                        482272
normal(3)                         413384
gpu_titanrtx(1)                   142287
normal(4)                         110565
normal(2)                         103142
normal(12)                         97512
normal(8)                          85811
gpu(1)                             80929
normal(5)                          65272
normal(20)                         45460
shared(5)                          21951
shared_jupyter(1)                  20267
shared(2)                          16563
gpu_titanrtx_shared_course(1)      11672
gpu_shared_course(1)                9532
Name: count, dtype: Int64

Número de nodos por job:

count    1.193073e+07
mean     2.358040e+00
std      3.745616e+00
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      3.200000e+01
Name: numnodes, dtype: float64

Número de cores por job:

count    1.193073e+07
mean     3.291527e+01
std      6.193572e+01
min      1.000000e+00
25%      4.000000e+00
50%      1.600000e+01
75%      1.600000e+01
max      5.120000e+02
Name: numcores, dtype: float64

Duración de jobs en horas:

count    1.193073e+07
mean     5.315612e+01
std      4.250765e+01
min      0.000000e+00
25%      1.200333e+01
50%      4.404472e+01
75%      9.511167e+01
max      1.210078e+02
Name: job_duration_hours, dtype: float64

In [ ]:
# Revisa columnas numéricas principales
cols_to_check = [
    "node_power_usage",
    "node_rapl_package_power_sum",
    "node_energy_kwh_est",
    "cpu_package_energy_kwh",
    "co2_kg_est",
    "node_load1",
    "node_load5",
    "node_load15",
    "node_load1_per_core",
    "ram_active_gb",
    "ram_free_gb",
    "node_hwmon_temp_celsius_mean",
    "node_hwmon_temp_celsius_max",
    "node_thermal_zone_temp_mean",
    "node_thermal_zone_temp_max",
    "gpu_power_watts_mean",
    "gpu_power_watts_max",
    "gpu_memory_used_gb",
    "nvidia_gpu_temperature_celsius_mean",
    "nvidia_gpu_temperature_celsius_max",
    "nvidia_gpu_duty_cycle_mean",
    "nvidia_gpu_duty_cycle_max"
]

existing_cols_to_check = [col for col in cols_to_check if col in df_core.columns]

summary_check = df_core[existing_cols_to_check].describe().T

display(summary_check)

,count,mean,std,min,25%,50%,75%,max
node_power_usage,11930727.0,325.043732,391.433674,32.000000,116.000000,152.000000,192.000000,1680.000000
node_rapl_package_power_sum,11930727.0,77.652777,31.465877,0.000000,57.698667,81.870333,100.826333,13697.225000
node_energy_kwh_est,11930727.0,0.002709,0.003263,0.000267,0.000967,0.001267,0.001600,0.086000
cpu_package_energy_kwh,11930727.0,0.000647,0.000262,0.000000,0.000481,0.000682,0.000840,0.114144
co2_kg_est,11930727.0,0.001084,0.001305,0.000107,0.000387,0.000507,0.000640,0.034400
node_load1,11930727.0,11.754406,26.542577,0.000000,2.480000,11.000000,15.600000,2446.860000
node_load5,11930727.0,11.731185,26.337468,0.000000,2.700000,10.920000,15.390000,2438.310000
node_load15,11930727.0,11.675485,26.001785,0.000000,3.000000,10.790000,15.220000,2421.850000
node_load1_per_core,11930727.0,1.654823,3.320564,0.000000,0.100812,0.730000,2.002500,180.930000
ram_active_gb,11930727.0,18.156516,17.869735,0.076820,3.744932,13.396144,29.663462,195.442699
ram_free_gb,11930727.0,91.958977,46.650191,0.274269,61.863009,85.245073,90.393331,249.563716
node_hwmon_temp_celsius_mean,11930727.0,39.691749,10.112084,21.390000,30.310000,40.110000,47.590000,71.410000
node_hwmon_temp_celsius_max,11930727.0,43.063875,9.946693,24.000000,35.000000,44.000000,50.000000,73.000000
node_thermal_zone_temp_mean,11930727.0,42.293068,9.859229,22.500000,34.500000,44.000000,49.500000,76.000000
node_thermal_zone_temp_max,11930727.0,43.249698,9.940631,23.000000,36.000000,44.000000,50.000000,76.000000
gpu_power_watts_mean,11930727.0,29.638081,65.145189,0.000000,0.000000,0.000000,0.000000,313.690250
gpu_power_watts_max,11930727.0,46.684967,95.636506,0.000000,0.000000,0.000000,0.000000,413.922000
gpu_memory_used_gb,11930727.0,7.064003,17.026592,0.000000,0.000000,0.000000,0.000000,93.894043
nvidia_gpu_temperature_celsius_mean,11930727.0,12.726830,24.426510,0.000000,0.000000,0.000000,0.000000,86.750000
nvidia_gpu_temperature_celsius_max,11930727.0,15.922117,30.171767,0.000000,0.000000,0.000000,0.000000,93.000000
nvidia_gpu_duty_cycle_mean,11930727.0,10.297634,24.310302,0.000000,0.000000,0.000000,0.000000,100.000000
nvidia_gpu_duty_cycle_max,11930727.0,16.741879,35.113484,0.000000,0.000000,0.000000,0.000000,100.000000

In [ ]:
# Revisa valores negativos en columnas numéricas principales
non_negative_cols = [
    "node_power_usage",
    "node_energy_kwh_est",
    "cpu_package_energy_kwh",
    "co2_kg_est",
    "ram_active_gb",
    "ram_free_gb",
    "gpu_power_watts_mean",
    "gpu_power_watts_max",
    "gpu_memory_used_gb",
    "node_disk_read_bytes_total_sum_delta",
    "node_disk_written_bytes_total_sum_delta",
    "node_network_receive_bytes_total_sum_delta",
    "node_network_transmit_bytes_total_sum_delta"
]

non_negative_cols = [col for col in non_negative_cols if col in df_core.columns]

print("Valores negativos por columna:")
for col in non_negative_cols:
    negatives = (df_core[col] < 0).sum()
    print(f"{col}: {negatives}")

Valores negativos por columna:
node_power_usage: 0
node_energy_kwh_est: 0
cpu_package_energy_kwh: 0
co2_kg_est: 0
ram_active_gb: 0
ram_free_gb: 0
gpu_power_watts_mean: 0
gpu_power_watts_max: 0
gpu_memory_used_gb: 0
node_disk_read_bytes_total_sum_delta: 0
node_disk_written_bytes_total_sum_delta: 0
node_network_receive_bytes_total_sum_delta: 0
node_network_transmit_bytes_total_sum_delta: 0

In [ ]:
# Revisa duplicados
print("Filas duplicadas completas:")
print(df_core.duplicated().sum())

print("\nDuplicados por prom_id:")
if "prom_id" in df_core.columns:
    print(df_core["prom_id"].duplicated().sum())

Filas duplicadas completas:
0

Duplicados por prom_id:
3472807

In [ ]:
# Revisa columnas clave
key_cols = [
    "timestamp",
    "node",
    "rack_inferred",
    "node_position_inferred",
    "gpu_node",
    "gpu_model",
    "node_load1",
    "node_power_usage",
    "node_hwmon_temp_celsius_mean",
    "ram_active_gb",
    "gpu_power_watts_mean",
    "nvidia_gpu_temperature_celsius_mean",
    "slurm_id",
    "state",
    "start_date",
    "end_date",
    "job_duration_hours"
]

key_cols = [col for col in key_cols if col in df_core.columns]

display(df_core[key_cols].head(30))

,timestamp,node,rack_inferred,node_position_inferred,gpu_node,gpu_model,node_load1,node_power_usage,node_hwmon_temp_celsius_mean,ram_active_gb,gpu_power_watts_mean,nvidia_gpu_temperature_celsius_mean,slurm_id,state,start_date,end_date,job_duration_hours
0,2022-07-28 22:58:30,r26n7,r26,n7,0,n/a,3.07,116.0,35.39,9.150784,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
1,2022-07-28 22:59:00,r26n7,r26,n7,0,n/a,3.04,116.0,35.33,9.151567,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
2,2022-07-28 22:59:30,r26n7,r26,n7,0,n/a,3.02,116.0,35.39,9.151474,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
3,2022-07-28 23:00:00,r26n7,r26,n7,0,n/a,3.01,116.0,35.06,9.151725,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
4,2022-07-28 23:00:30,r26n7,r26,n7,0,n/a,3.01,116.0,35.17,9.152535,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
5,2022-07-28 23:01:00,r26n7,r26,n7,0,n/a,3.00,116.0,35.17,9.152386,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
6,2022-07-28 23:01:30,r26n7,r26,n7,0,n/a,3.00,116.0,35.11,9.151157,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
7,2022-07-28 23:02:00,r26n7,r26,n7,0,n/a,2.78,116.0,34.89,7.820567,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
8,2022-07-28 23:02:30,r26n7,r26,n7,0,n/a,2.47,116.0,34.67,7.820725,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
9,2022-07-28 23:03:00,r26n7,r26,n7,0,n/a,2.44,116.0,34.78,7.834649,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
10,2022-07-28 23:03:30,r26n7,r26,n7,0,n/a,2.63,116.0,34.50,7.820865,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
11,2022-07-28 23:04:00,r26n7,r26,n7,0,n/a,2.38,116.0,34.50,7.819813,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
12,2022-07-28 23:04:30,r26n7,r26,n7,0,n/a,2.23,112.0,34.33,7.819543,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
13,2022-07-28 23:05:00,r26n7,r26,n7,0,n/a,2.14,112.0,34.44,7.820288,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
14,2022-07-28 23:05:30,r26n7,r26,n7,0,n/a,2.08,112.0,34.33,7.820362,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
15,2022-07-28 23:06:00,r26n7,r26,n7,0,n/a,2.05,112.0,34.50,7.819636,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
16,2022-07-28 23:06:30,r26n7,r26,n7,0,n/a,1.69,112.0,33.67,6.487416,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
17,2022-07-28 23:07:00,r26n7,r26,n7,0,n/a,1.41,112.0,33.44,6.488385,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
18,2022-07-28 23:07:30,r26n7,r26,n7,0,n/a,1.25,112.0,33.33,6.488133,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
19,2022-07-28 23:08:00,r26n7,r26,n7,0,n/a,1.15,112.0,33.06,6.487388,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
20,2022-07-28 23:08:30,r26n7,r26,n7,0,n/a,3.67,100.0,37.11,10.720920,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
21,2022-07-28 23:09:00,r26n7,r26,n7,0,n/a,4.83,100.0,38.11,10.657683,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
22,2022-07-28 23:09:30,r26n7,r26,n7,0,n/a,5.29,100.0,38.33,10.783505,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
23,2022-07-28 23:10:00,r26n7,r26,n7,0,n/a,5.57,100.0,38.56,10.890607,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
24,2022-07-28 23:10:30,r26n7,r26,n7,0,n/a,5.90,100.0,38.50,11.016615,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
25,2022-07-28 23:11:00,r26n7,r26,n7,0,n/a,5.94,100.0,38.39,11.111330,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
26,2022-07-28 23:11:30,r26n7,r26,n7,0,n/a,5.97,100.0,37.89,11.266861,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
27,2022-07-28 23:12:00,r26n7,r26,n7,0,n/a,5.58,100.0,37.67,10.713935,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
28,2022-07-28 23:12:30,r26n7,r26,n7,0,n/a,5.01,128.0,36.89,10.160357,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056
29,2022-07-28 23:13:00,r26n7,r26,n7,0,n/a,4.61,128.0,36.67,10.160264,0.0,0.0,1740264,COMPLETED,2022-07-28 05:00:01,2022-07-29 17:25:42,36.428056

In [16]:
memory_mb = df_core.memory_usage(deep=True).sum() / (1024 ** 2)

print(f"Tamaño aproximado en memoria: {memory_mb:.2f} MB")
print(f"Tamaño del archivo en disco: {DATASET_PATH.stat().st_size / (1024 ** 2):.2f} MB")

Tamaño aproximado en memoria: 9720.77 MB
Tamaño del archivo en disco: 716.44 MB